stages:
  - build
  - deploy

docker build_master:
  stage: build
  except:
   - schedules
  only:
   - master
  script:
  - cd docker/ci/ubuntu1804/master && docker build -t qcor/master-ci . --no-cache
  - docker system prune -f
  - docker rmi -f qcor/master-ci
  - git config remote.aideqcqcor.url >&- || git remote add -t master aideqcqcor https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/qcor
  - git push -f aideqcqcor HEAD:master
  - git remote remove aideqcqcor

# builds xacc and qcor bottles nightly
docker run_brew_linux_bottles:
  stage: deploy
  only:
   - schedules
  script:
  - git clone https://github.com/aide-qc/homebrew-deploy
  - cd homebrew-deploy/scripts/linux-x86_64
  - docker build --build-arg AIDEQC_ACCESS_TOKEN=$AIDEQC_ACCESS_TOKEN --build-arg JFROG_API_KEY=$JFROG_API_KEY -t qcor/brew-linux . --no-cache
  - docker system prune -f
  - docker rmi -f qcor/brew-linux

docker run_macosx_catalina_bottles:
  stage: deploy
  only:
    - schedules
  tags: 
    - osx
  script:
  - cd catalina && docker run -d -it --name tmp_catalina_ci --device /dev/kvm -p 50922:10022 -v "${PWD}/mac_hdd_ng.img:/image" sickcodes/docker-osx:naked
  - sleep 240
  - ssh catalina-ci "PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin bash run_bottle_build.sh $AIDEQC_ACCESS_TOKEN"
  - docker stop tmp_catalina_ci && docker rm -v tmp_catalina_ci
  
docker run_macosx_mojave_bottles:
  stage: deploy
  only:
    - schedules
  tags: 
    - mojave
  script:
  - cd mojave && docker run -d -it --name tmp_mojave_ci --device /dev/kvm -p 50922:10022 -v "${PWD}/mac_hdd_ng.img:/image" sickcodes/docker-osx:naked
  - sleep 240
  - ssh mojave-ci "PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin bash run_bottle_build.sh $AIDEQC_ACCESS_TOKEN"
  - docker stop tmp_mojave_ci && docker rm -v tmp_mojave_ci  