stages:
  - build
  - deploy

docker build_master:
  stage: build
  except:
   - schedules
  only:
   - master
  script:
  - cd docker/ci/ubuntu1804/master && docker build -t qcor/master-ci . --no-cache
  - docker system prune -f
  - docker rmi -f qcor/master-ci
  - git config remote.aideqcqcor.url >&- || git remote add -t master aideqcqcor https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/qcor
  - git push -f aideqcqcor HEAD:master
  - git remote remove aideqcqcor
  - git clone https://github.com/aide-qc/homebrew-deploy && cd homebrew-deploy 
  - wget https://github.com/ornl-qci/qcor/tarball/master && mv master qcor.tar.gz 
  - export src_sha=$(sha256sum qcor.tar.gz | cut -d " " -f 1)
  - sed -i "0,/sha256 \".*\"/s//sha256 \"$src_sha\" /" Formula/qcor.rb
  - git add Formula/qcor.rb
  - git commit -m "updating sha256 for qcor homebrew formula"
  - git config remote.aideqchbdeploy.url >&- || git remote add -t master aideqchbdeploy https://amccaskey:$AIDEQC_ACCESS_TOKEN@github.com/aide-qc/homebrew-deploy
  - git push -f aideqchbdeploy HEAD:master
  - git remote remove aideqchbdeploy

docker run_docker_deploy:
  stage: deploy
  only:
   - schedules
  script:
  - cd docker/deploy/dev && docker build -t qcor/qcor . --no-cache
  - echo "$REGISTRY_PASSWORD" | docker login -u qcor --password-stdin
  - docker push qcor/qcor
  - docker system prune -f
  - docker rmi -f qcor/qcor 

# builds xacc and qcor bottles nightly
docker run_brew_linux_bottles:
  stage: deploy
  only:
   - schedules
  script:
  - git clone https://github.com/aide-qc/homebrew-deploy
  - cd homebrew-deploy/scripts/linux-x86_64
  - docker build --build-arg AIDEQC_ACCESS_TOKEN=$AIDEQC_ACCESS_TOKEN --build-arg JFROG_API_KEY=$JFROG_API_KEY -t qcor/brew-linux . --no-cache
  - docker system prune -f
  - docker rmi -f qcor/brew-linux

docker run_macosx_bottles:
  stage: deploy
  only:
    - schedules
  tags: 
    - osx
  script:
  - docker start catalina-ci-container
  # give it time to boot up
  - sleep 120
  - ssh catalina-ci "git clone https://github.com/aide-qc/homebrew-deploy"
  - ssh catalina-ci "PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin bash homebrew-deploy/scripts/catalina/build.sh $AIDEQC_ACCESS_TOKEN $JFROG_API_KEY"
  - docker stop catalina-ci-container
  # now run mojave
  - docker start mojave-ci-container
  - sleep 120
  - ssh mojave-ci "git clone https://github.com/aide-qc/homebrew-deploy"
  - ssh mojave-ci "PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin bash homebrew-deploy/scripts/mojave/build.sh $AIDEQC_ACCESS_TOKEN $JFROG_API_KEY"
  - docker stop mojave-ci-container
  
